### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by EuropeanVirtual** [retoperrottet/EnergyAirBot2021#1]
Hello  the Location is not State de Suise Wankdorf
its Namend only  Stadion Wankdorf

**Comment by retoperrottet** [comment]
Hi, Thanks for the information, I didn’t change the question and answer, I just copied them from the 2021 version and it worked most of the Time. After a quick reasearch I realized that you are right. I‘ll change it asap and upload the updated version. Thanks!

**Comment by retoperrottet** [comment]
Issue is fixed. Thanks for your help! 👍🏼
